name: Continuous Integration

on: [pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: echo "MONGO_URI=${{ secrets.MONGO_URI_TEST }}" > backend/.env
      - name: Build Backend Images
        run: docker-compose build backend
      - name: Run Backend and Database Containers
        run: docker-compose up -d backend database
      - name: Run Test Backend Pipeline
        run: docker-compose exec -T backend poetry run test
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "higgs-bknd"
          heroku_email: "igormcsouza@gmail.com"
          usedocker: true
          appdir: "backend"
        env:
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
